language: node_js
node_js: 
  - "stable"
services: 
  docker
before_script:
  psql -d dbzbay -a -f init.sql  

cache:
  directories
  - "node_modules"

env:
  - DOCKER_COMPOSE_
  - PGUSER=travis
  - PGPASSWORD=travis
  - PGDATABASE=dbzbay
  - ENV=travis