language: node_js
node_js: 
  - "stable"
services: 
  docker

cache:
  directories
  - "node_modules"

env:
  - DOCKER_COMPOSE_
  - PGUSER=travis
  - PGPASSWORD=travis
  - PGDATABASE=dbzbay
  - ENV=travis