version: "3.7"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: DBZbay
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - '5432:5432'
  web:
    
      